import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import { motion } from 'framer-motion';
import Footer from '../components/Footer';
import Icons from '../components/Icons';
import { LICENSE_TIERS } from '../lib/seeds';

function FAQItem({ q, a, isOpen, onToggle }) {
  return (
    <div style={{
      background: 'var(--bg-card)', borderRadius: 'var(--radius-sm)',
      border: isOpen ? '1px solid var(--accent)33' : '1px solid var(--border)',
      overflow: 'hidden', transition: 'border-color 0.3s',
    }}>
      <button
        onClick={onToggle}
        style={{
          width: '100%', display: 'flex', justifyContent: 'space-between', alignItems: 'center',
          padding: '20px 24px', background: 'none', border: 'none', cursor: 'pointer',
          fontFamily: 'var(--font)', textAlign: 'left',
        }}
      >
        <span style={{ fontSize: 15, fontWeight: 600, color: 'var(--text-primary)' }}>{q}</span>
        <motion.span
          animate={{ rotate: isOpen ? 180 : 0 }}
          transition={{ duration: 0.25 }}
          style={{ color: 'var(--text-muted)', flexShrink: 0, marginLeft: 16, display: 'flex' }}
        >
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <polyline points="6 9 12 15 18 9" />
          </svg>
        </motion.span>
      </button>
      <div
        className="accordion-content"
        style={{
          maxHeight: isOpen ? 300 : 0,
          opacity: isOpen ? 1 : 0,
          padding: isOpen ? '0 24px 20px' : '0 24px',
        }}
      >
        <div style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.7 }}>{a}</div>
      </div>
    </div>
  );
}

export default function LicensingPage() {
  const [openFaq, setOpenFaq] = useState(null);

  const faqs = [
    { q: 'What do I get with each license?', a: 'Each license includes the beat file (MP3 and/or WAV depending on tier). Premium and above include WAV. Unlimited and Exclusive include stems. Exclusive means the beat is pulled from the store.' },
    { q: 'Can I use the beat commercially?', a: 'Yes! All licenses permit commercial use. The Basic lease is for smaller projects; Premium and above cover DSP distribution, radio, and more.' },
    { q: 'How do I receive my files?', a: 'After payment, you\'ll receive a secure download link via email. Links expire after 72 hours but can be regenerated by contacting us.' },
    { q: 'Can I get a custom beat?', a: 'Absolutely. Visit the Custom Production page to submit your project details, and I\'ll get back to you within 24-48 hours.' },
    { q: 'What if I want to upgrade my license?', a: 'Contact me and we\'ll work out the difference. Upgrades are always welcome.' },
  ];

  return (
    <>
      <Helmet>
        <title>Licensing Options — AJKEYZZZ</title>
        <meta name="description" content="Transparent beat licensing. Choose from Basic, Premium, Unlimited, or Exclusive licenses. Clear terms and instant delivery." />
      </Helmet>

      <div style={{ paddingTop: 100, maxWidth: 1000, margin: '0 auto', padding: '100px 24px 80px' }}>
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          style={{ textAlign: 'center', marginBottom: 60 }}
        >
          <div style={{
            fontSize: 'var(--text-xs)', fontFamily: 'var(--mono)', color: 'var(--accent)',
            textTransform: 'uppercase', letterSpacing: 'var(--tracking-wider)', marginBottom: 12, fontWeight: 600,
          }}>
            Transparent Pricing
          </div>
          <h1 style={{ fontSize: 40, fontWeight: 800, marginBottom: 8, letterSpacing: 'var(--tracking-tight)' }}>
            Licensing Options
          </h1>
          <p style={{ color: 'var(--text-secondary)', fontSize: 16, maxWidth: 600, margin: '0 auto' }}>
            Pick the license that matches your project scope. All licenses include instant delivery.
          </p>
        </motion.div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: 20 }}>
          {LICENSE_TIERS.map((tier, i) => (
            <motion.div
              key={tier.id}
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.4, delay: i * 0.1 }}
              whileHover={{ y: -4, transition: { duration: 0.2 } }}
              style={{
                background: 'var(--bg-card)', borderRadius: 'var(--radius)', padding: 32,
                border: tier.popular ? `2px solid ${tier.accent}` : '1px solid var(--border)',
                position: 'relative',
              }}
            >
              {tier.popular && (
                <div style={{
                  position: 'absolute', top: -12, left: '50%', transform: 'translateX(-50%)',
                  background: tier.accent, padding: '4px 16px', borderRadius: 20,
                  fontSize: 11, fontWeight: 700, letterSpacing: 1, textTransform: 'uppercase',
                }}>
                  Most Popular
                </div>
              )}
              {tier.id === 'premium' && (
                <div style={{
                  position: 'absolute', top: 12, right: 12,
                  background: 'var(--accent-green)18', color: 'var(--accent-green)',
                  padding: '3px 10px', borderRadius: 'var(--radius-pill)',
                  fontSize: 10, fontWeight: 700,
                }}>
                  Save 15%
                </div>
              )}
              <div style={{ fontSize: 16, fontWeight: 700, color: tier.accent, marginBottom: 12 }}>{tier.name}</div>
              <div style={{ fontSize: 36, fontWeight: 900, marginBottom: 4 }}>${tier.defaultPrice.toFixed(2)}</div>
              <div style={{ fontSize: 12, color: 'var(--text-muted)', marginBottom: 24 }}>starting at</div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 12, marginBottom: 28 }}>
                {tier.features.map((f, fi) => (
                  <div key={fi} style={{ fontSize: 13, color: 'var(--text-secondary)', display: 'flex', gap: 10 }}>
                    <span style={{ color: tier.accent }}>✓</span> {f}
                  </div>
                ))}
              </div>
              <Link
                to="/beats"
                style={{
                  display: 'block', width: '100%', padding: '14px 0', borderRadius: 50, textAlign: 'center',
                  background: tier.popular ? tier.accent : 'transparent',
                  border: tier.popular ? 'none' : `1px solid ${tier.accent}44`,
                  color: tier.popular ? '#fff' : tier.accent,
                  fontSize: 14, fontWeight: 600, cursor: 'pointer', fontFamily: 'var(--font)',
                  transition: 'all 0.2s', textDecoration: 'none',
                }}
              >
                Browse Beats
              </Link>
            </motion.div>
          ))}
        </div>

        {/* FAQ */}
        <motion.section
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          style={{ marginTop: 80 }}
        >
          <h2 style={{ fontSize: 28, fontWeight: 700, textAlign: 'center', marginBottom: 40, letterSpacing: 'var(--tracking-tight)' }}>
            Frequently Asked Questions
          </h2>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12, maxWidth: 700, margin: '0 auto' }}>
            {faqs.map(({ q, a }, i) => (
              <FAQItem
                key={q}
                q={q}
                a={a}
                isOpen={openFaq === i}
                onToggle={() => setOpenFaq(openFaq === i ? null : i)}
              />
            ))}
          </div>
        </motion.section>

        <div style={{ height: 60 }} />
        <Footer />
      </div>
    </>
  );
}
