import { Link } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import Footer from '../components/Footer';
import { LICENSE_TIERS } from '../lib/seeds';

export default function LicensingPage() {
  return (
    <>
      <Helmet>
        <title>Licensing Options — AJKEYZZZ</title>
        <meta name="description" content="Transparent beat licensing. Choose from Basic, Premium, Unlimited, or Exclusive licenses. Clear terms and instant delivery." />
      </Helmet>

      <div style={{ paddingTop: 100, maxWidth: 1000, margin: '0 auto', padding: '100px 24px 80px' }}>
        <div style={{ textAlign: 'center', marginBottom: 60 }}>
          <h1 style={{ fontSize: 40, fontWeight: 800, marginBottom: 8 }}>Licensing Options</h1>
          <p style={{ color: 'var(--text-secondary)', fontSize: 16, maxWidth: 600, margin: '0 auto' }}>
            Transparent pricing. Pick the license that matches your project scope.
          </p>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: 20 }}>
          {LICENSE_TIERS.map((tier) => (
            <div key={tier.id} style={{
              background: 'var(--bg-card)', borderRadius: 'var(--radius)', padding: 32,
              border: tier.popular ? `2px solid ${tier.accent}` : '1px solid var(--border)',
              position: 'relative', transition: 'transform 0.3s',
            }}>
              {tier.popular && (
                <div style={{
                  position: 'absolute', top: -12, left: '50%', transform: 'translateX(-50%)',
                  background: tier.accent, padding: '4px 16px', borderRadius: 20,
                  fontSize: 11, fontWeight: 700, letterSpacing: 1, textTransform: 'uppercase',
                }}>
                  Most Popular
                </div>
              )}
              <div style={{ fontSize: 16, fontWeight: 700, color: tier.accent, marginBottom: 12 }}>{tier.name}</div>
              <div style={{ fontSize: 36, fontWeight: 900, marginBottom: 4 }}>${tier.defaultPrice.toFixed(2)}</div>
              <div style={{ fontSize: 12, color: 'var(--text-muted)', marginBottom: 24 }}>starting at</div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 12, marginBottom: 28 }}>
                {tier.features.map((f, i) => (
                  <div key={i} style={{ fontSize: 13, color: 'var(--text-secondary)', display: 'flex', gap: 10 }}>
                    <span style={{ color: tier.accent }}>✓</span> {f}
                  </div>
                ))}
              </div>
              <Link
                to="/beats"
                style={{
                  display: 'block', width: '100%', padding: '14px 0', borderRadius: 50, textAlign: 'center',
                  background: tier.popular ? tier.accent : 'transparent',
                  border: tier.popular ? 'none' : `1px solid ${tier.accent}44`,
                  color: tier.popular ? '#fff' : tier.accent,
                  fontSize: 14, fontWeight: 600, cursor: 'pointer', fontFamily: 'var(--font)',
                  transition: 'all 0.2s', textDecoration: 'none',
                }}
              >
                Browse Beats
              </Link>
            </div>
          ))}
        </div>

        {/* FAQ */}
        <section style={{ marginTop: 80 }}>
          <h2 style={{ fontSize: 28, fontWeight: 700, textAlign: 'center', marginBottom: 40 }}>
            Frequently Asked Questions
          </h2>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 16, maxWidth: 700, margin: '0 auto' }}>
            {[
              { q: 'What do I get with each license?', a: 'Each license includes the beat file (MP3 and/or WAV depending on tier). Premium and above include WAV. Unlimited and Exclusive include stems. Exclusive means the beat is pulled from the store.' },
              { q: 'Can I use the beat commercially?', a: 'Yes! All licenses permit commercial use. The Basic lease is for smaller projects; Premium and above cover DSP distribution, radio, and more.' },
              { q: 'How do I receive my files?', a: 'After payment, you\'ll receive a secure download link via email. Links expire after 72 hours but can be regenerated by contacting us.' },
              { q: 'Can I get a custom beat?', a: 'Absolutely. Visit the Custom Production page to submit your project details, and I\'ll get back to you within 24-48 hours.' },
              { q: 'What if I want to upgrade my license?', a: 'Contact me and we\'ll work out the difference. Upgrades are always welcome.' },
            ].map(({ q, a }) => (
              <div key={q} style={{
                background: 'var(--bg-card)', borderRadius: 'var(--radius-sm)', padding: '20px 24px',
                border: '1px solid var(--border)',
              }}>
                <div style={{ fontSize: 15, fontWeight: 600, marginBottom: 8 }}>{q}</div>
                <div style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.6 }}>{a}</div>
              </div>
            ))}
          </div>
        </section>

        <div style={{ height: 60 }} />
        <Footer />
      </div>
    </>
  );
}
